# Generated by Django 4.1.1 on 2023-03-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created']},
        ),
    ]
